/*
 *  Copyright (C) 2017-2019 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
/**
 * \ingroup DRV_SCICLIENT_MODULE
 * \defgroup TISCI TISCI
 *
 * DMSC controls the power management, security and resource management
 * of the device.
 *
 *
 * @{
 */
/**
 *  \file   tisci_includes.h
 *
 *  \brief  This file includes the other tisci_* headers.
 *          WARNING!!: Autogenerated file from SYSFW. DO NOT MODIFY!!
 */

#ifndef TISCI_INCLUDES_H
#define TISCI_INCLUDES_H

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

/** This macro is used by the TISCI headers to indicate bit positions */
#define TISCI_BIT(n)  (1UL << (n))

#if defined (SOC_AM65XX)
#include <ti/drv/sciclient/soc/V0/tisci_resasg_types.h>
#include <ti/drv/sciclient/soc/V0/tisci_hosts.h>
#include <ti/drv/sciclient/soc/V0/tisci_sec_proxy.h>
#endif
#if defined (SOC_J721E)
#include <ti/drv/sciclient/soc/V1/tisci_resasg_types.h>
#include <ti/drv/sciclient/soc/V1/tisci_hosts.h>
#include <ti/drv/sciclient/soc/V1/tisci_sec_proxy.h>
#endif
#include <ti/drv/sciclient/include/tisci/tisci_core.h>
#include <ti/drv/sciclient/include/tisci/security/tisci_keystore.h>
#include <ti/drv/sciclient/include/tisci/security/tisci_sa2ul_pka.h>
#include <ti/drv/sciclient/include/tisci/security/tisci_sec_macros.h>
#include <ti/drv/sciclient/include/tisci/security/tisci_rng.h>
#include <ti/drv/sciclient/include/tisci/security/tisci_procboot.h>
#include <ti/drv/sciclient/include/tisci/security/tisci_firewall.h>
#include <ti/drv/sciclient/include/tisci/tisci_boardcfg.h>
#include <ti/drv/sciclient/include/tisci/pm/tisci_pm_device.h>
#include <ti/drv/sciclient/include/tisci/pm/tisci_pm_core.h>
#include <ti/drv/sciclient/include/tisci/pm/tisci_pm_clock.h>
#include <ti/drv/sciclient/include/tisci/tisci_boardcfg_constraints.h>
#include <ti/drv/sciclient/include/tisci/tisci_protocol.h>
#include <ti/drv/sciclient/include/tisci/rm/tisci_rm_core.h>
#include <ti/drv/sciclient/include/tisci/rm/tisci_rm_udmap.h>
#include <ti/drv/sciclient/include/tisci/rm/tisci_rm_shared.h>
#include <ti/drv/sciclient/include/tisci/rm/tisci_rm_irq.h>
#include <ti/drv/sciclient/include/tisci/rm/tisci_rm_ra.h>
#include <ti/drv/sciclient/include/tisci/rm/tisci_rm_psil.h>

#endif /* TISCI_INCLUDES_H */

/* @} */
